Header/Nav Block.
hlxsites/takeda-ihs pull request #23
Opened 2023-06-12 19:29 UTC by bstopp

Fix #2 

Test URLs:
- After: https://feat-nav--takeda-ihs--hlxsites.hlx.page/

2023-06-13 18:29 UTC, lwintch commented on blocks/footer/footer.js
> +// import { readBlockConfig, decorateIcons } from '../../scripts/lib-franklin.js';
Are we good to leave comments in for now?  Maybe until the next phase?

2023-06-13 18:31 UTC, bstopp commented on blocks/header/header.css
> +  background-color: white;
Yes, see the `styles.css` file - but in this case, i wanted literal white. I'm fine moving this to a var and referencing that.

2023-06-13 18:37 UTC, lwintch approved these changes
Looks solid.  There's only 1 thing in the behavior I noticed, and that's on touch devices.  The menus don't really open as the arrow controls go to the same target as the menu name when clicked.  If that's not a concern right now, everything else looks good.

2023-06-13 18:39 UTC, lwintch commented on blocks/header/header.css
> +  background-color: white;
No preference here.  I thought literal white always mapped to `#fff`, but it's not a hill I'm fighting on.  No worries.

2023-06-14 17:29 UTC, lwintch requested changes
Removing approval over issue discussed.  Will re-approve shortly after the fix is in.

2023-06-15 16:22 UTC, lwintch approved these changes
Checked again, looks good.

2023-06-15 16:26 UTC, merged