Unordered list block for Triple Aim
hlxsites/takeda-ihs pull request #58
Opened 2023-07-18 22:10 UTC by lwintch

Adding the Triple Aim content block using an unordered list.

Fix #12

Test URLs:
- After:  https://feat-triple-aim-bars--takeda-ihs--hlxsites.hlx.page/drafts/lists

2023-07-24 19:42 UTC, lwintch commented
@bstopp could you review this when you get a chance?

2023-07-25 13:54 UTC, bstopp requested changes
Just need to remove the lazy loading of the image.

2023-07-25 13:54 UTC, bstopp commented on blocks/lists/lists.js
> +export default async function decorate(block) {
This isn't needed - the default for all but the first image on the page is lazy, and we want the FCP to not be lazy.

2023-07-25 17:57 UTC, bstopp approved these changes

2023-07-25 17:57 UTC, merged